/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Nis2KonsultRouteImport } from './routes/nis2-konsult'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as IntegritetRouteImport } from './routes/integritet'
import { Route as ForKonsulterRouteImport } from './routes/for-konsulter'
import { Route as BedomningRouteImport } from './routes/bedomning'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BranscherIndexRouteImport } from './routes/branscher.index'
import { Route as StadSlugRouteImport } from './routes/stad.$slug'
import { Route as BranscherSlugRouteImport } from './routes/branscher.$slug'

const Nis2KonsultRoute = Nis2KonsultRouteImport.update({
  id: '/nis2-konsult',
  path: '/nis2-konsult',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegritetRoute = IntegritetRouteImport.update({
  id: '/integritet',
  path: '/integritet',
  getParentRoute: () => rootRouteImport,
} as any)
const ForKonsulterRoute = ForKonsulterRouteImport.update({
  id: '/for-konsulter',
  path: '/for-konsulter',
  getParentRoute: () => rootRouteImport,
} as any)
const BedomningRoute = BedomningRouteImport.update({
  id: '/bedomning',
  path: '/bedomning',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BranscherIndexRoute = BranscherIndexRouteImport.update({
  id: '/branscher/',
  path: '/branscher/',
  getParentRoute: () => rootRouteImport,
} as any)
const StadSlugRoute = StadSlugRouteImport.update({
  id: '/stad/$slug',
  path: '/stad/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BranscherSlugRoute = BranscherSlugRouteImport.update({
  id: '/branscher/$slug',
  path: '/branscher/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bedomning': typeof BedomningRoute
  '/for-konsulter': typeof ForKonsulterRoute
  '/integritet': typeof IntegritetRoute
  '/kontakt': typeof KontaktRoute
  '/nis2-konsult': typeof Nis2KonsultRoute
  '/branscher/$slug': typeof BranscherSlugRoute
  '/stad/$slug': typeof StadSlugRoute
  '/branscher/': typeof BranscherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bedomning': typeof BedomningRoute
  '/for-konsulter': typeof ForKonsulterRoute
  '/integritet': typeof IntegritetRoute
  '/kontakt': typeof KontaktRoute
  '/nis2-konsult': typeof Nis2KonsultRoute
  '/branscher/$slug': typeof BranscherSlugRoute
  '/stad/$slug': typeof StadSlugRoute
  '/branscher': typeof BranscherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bedomning': typeof BedomningRoute
  '/for-konsulter': typeof ForKonsulterRoute
  '/integritet': typeof IntegritetRoute
  '/kontakt': typeof KontaktRoute
  '/nis2-konsult': typeof Nis2KonsultRoute
  '/branscher/$slug': typeof BranscherSlugRoute
  '/stad/$slug': typeof StadSlugRoute
  '/branscher/': typeof BranscherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bedomning'
    | '/for-konsulter'
    | '/integritet'
    | '/kontakt'
    | '/nis2-konsult'
    | '/branscher/$slug'
    | '/stad/$slug'
    | '/branscher/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bedomning'
    | '/for-konsulter'
    | '/integritet'
    | '/kontakt'
    | '/nis2-konsult'
    | '/branscher/$slug'
    | '/stad/$slug'
    | '/branscher'
  id:
    | '__root__'
    | '/'
    | '/bedomning'
    | '/for-konsulter'
    | '/integritet'
    | '/kontakt'
    | '/nis2-konsult'
    | '/branscher/$slug'
    | '/stad/$slug'
    | '/branscher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BedomningRoute: typeof BedomningRoute
  ForKonsulterRoute: typeof ForKonsulterRoute
  IntegritetRoute: typeof IntegritetRoute
  KontaktRoute: typeof KontaktRoute
  Nis2KonsultRoute: typeof Nis2KonsultRoute
  BranscherSlugRoute: typeof BranscherSlugRoute
  StadSlugRoute: typeof StadSlugRoute
  BranscherIndexRoute: typeof BranscherIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nis2-konsult': {
      id: '/nis2-konsult'
      path: '/nis2-konsult'
      fullPath: '/nis2-konsult'
      preLoaderRoute: typeof Nis2KonsultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integritet': {
      id: '/integritet'
      path: '/integritet'
      fullPath: '/integritet'
      preLoaderRoute: typeof IntegritetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-konsulter': {
      id: '/for-konsulter'
      path: '/for-konsulter'
      fullPath: '/for-konsulter'
      preLoaderRoute: typeof ForKonsulterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bedomning': {
      id: '/bedomning'
      path: '/bedomning'
      fullPath: '/bedomning'
      preLoaderRoute: typeof BedomningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branscher/': {
      id: '/branscher/'
      path: '/branscher'
      fullPath: '/branscher/'
      preLoaderRoute: typeof BranscherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stad/$slug': {
      id: '/stad/$slug'
      path: '/stad/$slug'
      fullPath: '/stad/$slug'
      preLoaderRoute: typeof StadSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branscher/$slug': {
      id: '/branscher/$slug'
      path: '/branscher/$slug'
      fullPath: '/branscher/$slug'
      preLoaderRoute: typeof BranscherSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BedomningRoute: BedomningRoute,
  ForKonsulterRoute: ForKonsulterRoute,
  IntegritetRoute: IntegritetRoute,
  KontaktRoute: KontaktRoute,
  Nis2KonsultRoute: Nis2KonsultRoute,
  BranscherSlugRoute: BranscherSlugRoute,
  StadSlugRoute: StadSlugRoute,
  BranscherIndexRoute: BranscherIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
